applications:
  static_site_dotnet:
    source:
      root: "web"  # تحديد مسار جذر الملفات الثابتة
    type: "dotnet"
    build:
      flavor: none  # لا يوجد بناء إضافي مطلوب للصفحات الثابتة
    dependencies:
      dotnet: "5.0"  # تحديد إصدار .NET Core المستخدم

routes:
  "https://{default}/":
    type: upstream
    upstream: "static_site_dotnet:web"

  "https://www.{default}/":
    type: redirect
    to: "https://{default}/"
