applications:
  static_site_dotnet:
    source:
      root: "web"
    type: "dotnet:5.0"  # تحديد إصدار .NET Core المستخدم
    build:
      flavor: none
    dependencies:
      dotnet: "5.0"

routes:
  "https://{default}/":
    type: upstream
    upstream: "static_site_dotnet:web"

  "https://www.{default}/":
    type: redirect
    to: "https://{default}/"
